name: plot observables

on:
  push:
    branches:
      - main
      - release-candidate
      - JETSCAPE-3.5.1-RC
      - latessa/generalizedTests

env:
  PULL_NUMBER: ${{ github.event.number }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: Run_Plot_Test
    runs-on: ubuntu-latest
    
    container:
      image: jetscape/base:stable
      options: --user root
      
    steps:
      
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}
      
    - name: Build Application
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}
        mkdir build
        cd build
        cmake ..
        make -j2

    - name: Generate pp events
      run: |
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/build
        ${GITHUB_WORKSPACE}/${REPO_NAME}/build/runJetscape ${GITHUB_WORKSPACE}/${REPO_NAME}/test/pp/config/jetscape_user_PP19_weighted.xml ${GITHUB_WORKSPACE}/${REPO_NAME}/config/jetscape_main.xml

    - name: Plot observables
      run: |
        echo ${PULL_NUMBER}
        ${GITHUB_WORKSPACE}/${REPO_NAME}/test/generate_plots.sh -j ${GITHUB_WORKSPACE}/${REPO_NAME} -o ${GITHUB_WORKSPACE}/${REPO_NAME}/test/plot/output/new

    - name: Prepare TAR file for transfer
      run: |
        export ET=`date "+%Y%m%d%H%M%S"`
        mkdir ${GITHUB_WORKSPACE}/${REPO_NAME}/test/plot/output/archive
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/test/plot/output/new
        tar -cvzf ${GITHUB_WORKSPACE}/${REPO_NAME}/test/plot/output/archive/files_${ET}.tar.gz .
        cd ${GITHUB_WORKSPACE}/${REPO_NAME}/test/plot/output/archive
        echo "pwd of archive"
        pwd
        echo "ls of archive"
        ls
        
    - name: Deploy Plots
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: "ftp.joelatessa.com"
        user: "jetscapeTest@plot.joelatessa.com"
        password: ${{ secrets.JETSCAPE_FTP_PASS }}
        local_dir: "./${{ github.event.repository.name }}/test/plot/output/archive"
        remote_dir: "./"
        delete: "false"
